require "colorize"
require "string_inflection"
require "html"
require "baked_file_system"
require "kemal"

require "./errors/**"
require "./ext/**"

require "./messages"
require "./assets"
require "./logger"
require "./utils/**"
require "./type_checker"
require "./formatter"
require "./compiler"
require "./installer"
require "./builder"
require "./parser"
require "./test"
require "./ast"
require "./cli"

require "./nodes/**"
